### PR TITLE
Yield configuration for each pipeline unit that should be instantiated

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/adviser/issues/1666

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
:1234:

**Comment by fridex** [comment]
Looks like a bug in black?

```
error: cannot format /home/prow/go/src/github.com/thoth-station/adviser/thoth/adviser/steps/security_indicators.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_jqotfzfg.log
Oh no! 💥 💔 💥
```

**Comment by fridex** [comment]
/approve

Double-checked. I will proceed with this one to continue with work.

**Pull request merged**
