### PR TITLE
Adjust the default link to Thoth search

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## Description

Adjust the link to Thoth's search UI used by default.

### CODE REVIEW

**Comment by fridex** [comment]
/assign @Gkrumbach07 

PTAL.

**Comment by goern** [comment]
https://thoth-station.ninja/search/ gives me some 404, looks like the site is not fully deployed?! @Gkrumbach07

**Comment by Gkrumbach07** [comment]
> https://thoth-station.ninja/search/ gives me some 404, looks like the site is not fully deployed?! @Gkrumbach07

It is, but is currently failing because the repo name was changed to search. This breaks routing but its a simple change
 I was planning on pushing today along with the addition of the other test deployment.

**Comment by Gkrumbach07** [comment]
LGTM

**Comment by fridex** [comment]
The issue is caused by an update of thoth-common. I will address it in a separate PR.

**Pull request merged**
