### PR TITLE
Add a generic alias pseudonym unit

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by goern** [comment]
@fridex could you turn the test case in a small screencast, so we have a demo for this feature? I think it is required for https://github.com/thoth-station/core/blob/master/doc/ROADMAP.md#optimizing-deployment-pipeline

@pacospace @sub-mod

**Comment by fridex** [comment]
> @fridex could you turn the test case in a small screencast, so we have a demo for this feature? I think it is required for https://github.com/thoth-station/core/blob/master/doc/ROADMAP.md#optimizing-deployment-pipeline
> 
> @pacospace @sub-mod

Yes, I can do that. You can also find a jupyter notebook demonstrating this feature here:

https://github.com/thoth-station/notebooks/blob/master/notebooks/development/Pipeline%20units.ipynb

**Comment by fridex** [comment]
> @fridex could you turn the test case in a small screencast, so we have a demo for this feature? I think it is required for https://github.com/thoth-station/core/blob/master/doc/ROADMAP.md#optimizing-deployment-pipeline

https://www.youtube.com/watch?v=OCX8JQDXP9s

**Pull request merged**
