### PR TITLE
Derive information from trove classifiers for users

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/1850

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

Requires a new thoth-storages release with a new trove classifiers query.

**Review by pacospace — COMMENTED** [review]
lgtm! 💯  please take care of tests :)

**Comment by fridex** [comment]
All green, merging.

**Pull request merged**
