### PR TITLE
Update TensorFlow symbols database

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/tensorflow-symbols/pull/6 https://github.com/thoth-station/tensorflow-symbols/pull/5
Fixes: https://github.com/thoth-station/adviser/issues/1586

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

some are still missing, checking

**Comment by fridex** [comment]
/unhold

ready to review

**Review by harshad16 — COMMENTED** [review]
Is this generated through a API call run from tensorflow-symbol project?

**Comment by fridex** [comment]
> Is this generated through a API call run from tensorflow-symbol project?

Yes :+1:

**Review by harshad16 — APPROVED** [review]
thanks, lgtm

**Pull request merged**
