### PR TITLE
Disable provenance checks

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
> could you update the description and state why we don't want the prov chk?

Our database needs to be updated to keep up with recent releases, otherwise provenance blocks the build:


```
2020-04-02 23:17:07,090 [23] DEBUG    thamos.lib: Elapsed seconds processing request: 3.307969
--
  | Digest   \|     Id     \| Justifica \|  Package  \|  Package  \| Source \|   Type
  | \|            \|   tion    \|   name    \|  version  \|        \|
  | ===========+============+===========+===========+===========+========+==========
  | e4bbbb1a79 \| INVALID-   \| Hash for  \| jsonforma \|   ==0.1.4 \| None   \|
  | 013d2f4b1d \| ARTIFACT-  \| the given \|   tter    \|           \|        \|    ❌
  | 249fbed755 \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | ade679fd03 \|            \| was not   \|           \|           \|        \|
  | af9a40de8e \|            \| found     \|           \|           \|        \|
  | 45148cde3d \|            \|           \|           \|           \|        \|
  | 21af       \|            \|           \|           \|           \|        \|
  | 13d3144e1e \| INVALID-   \| Hash for  \| markupsaf \|   ==1.1.1 \| None   \|
  | 340870b25e \| ARTIFACT-  \| the given \|     e     \|           \|        \|    ❌
  | 7b10b98d77 \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | 9608c02016 \|            \| was not   \|           \|           \|        \|
  | d5184cfb99 \|            \| found     \|           \|           \|        \|
  | 27a9f10c68 \|            \|           \|           \|           \|        \|
  | 9f42       \|            \|           \|           \|           \|        \|
  | 596510de11 \| INVALID-   \| Hash for  \| markupsaf \|   ==1.1.1 \| None   \|
  | 2c68548909 \| ARTIFACT-  \| the given \|     e     \|           \|        \|    ❌
  | 5da617b5bc \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | bbac7dd638 \|            \| was not   \|           \|           \|        \|
  | 4aeebeda4d \|            \| found     \|           \|           \|        \|
  | f6025d0256 \|            \|           \|           \|           \|        \|
  | a81b       \|            \|           \|           \|           \|        \|
  | 6788b695d5 \| INVALID-   \| Hash for  \| markupsaf \|   ==1.1.1 \| None   \|
  | 0a51edb699 \| ARTIFACT-  \| the given \|     e     \|           \|        \|    ❌
  | cb55e35487 \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | e430fa21f1 \|            \| was not   \|           \|           \|        \|
  | ed838122d7 \|            \| found     \|           \|           \|        \|
  | 22e0ff0ac5 \|            \|           \|           \|           \|        \|
  | ba15       \|            \|           \|           \|           \|        \|
  | cdb132fc82 \| INVALID-   \| Hash for  \| markupsaf \|   ==1.1.1 \| None   \|
  | 5c38e1aeec \| ARTIFACT-  \| the given \|     e     \|           \|        \|    ❌
  | 2c8aa93383 \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | 10d29d337b \|            \| was not   \|           \|           \|        \|
  | ebbd7baa06 \|            \| found     \|           \|           \|        \|
  | 889d09a60a \|            \|           \|           \|           \|        \|
  | 1fa2       \|            \|           \|           \|           \|        \|
  | e8313f01ba \| INVALID-   \| Hash for  \| markupsaf \|   ==1.1.1 \| None   \|
  | 26fbbe36c7 \| ARTIFACT-  \| the given \|     e     \|           \|        \|    ❌
  | be1966a7b7 \| HASH       \| artifact  \|           \|           \|        \| ERROR
  | 424942f670 \|            \| was not   \|           \|           \|        \|
  | f38e666995 \|            \| found     \|           \|           \|        \|
  | b88d012765 \|            \|           \|           \|           \|        \|
  | b9be       \|            \|           \|           \|           \|        \|
```

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Pull request merged**
