### PR TITLE
Add a sieve to filter out packages based on ABI provided by s2i Thoth

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/issues/1631
Depends-On: https://github.com/thoth-station/storages/pull/2193
Depends-On: https://github.com/thoth-station/storages/pull/2195

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/assign @KPostOffice 

Kevin, please have a look at this one. It's based on your sieve for filtering out packages based on ABI symbols present in the environment. As the query for obtaining ABI symbols present in the container image was not specific to a concrete container image, this implementation tigthly couples Thoth s2i base container image with the query so we know exactly which Thoth s2i container image is used and what ABI symbols it offers.

Tests will fail as this change requires a new release of thoth-storages with linked PRs.

**Review by KPostOffice — APPROVED** [review]
LGTM :+1:

**Comment by fridex** [comment]
The tests will fail due to https://github.com/thoth-station/adviser/pull/1641. I will merge this. @KPostOffice Thanks for the review :+1:

**Pull request merged**
