### PR TITLE
Warn users if they provide too lax version range specifiers

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
> @fridex Correct me if I am wrong but, I remember that a `stack_info` param was not provided when a OOM error occurred. So these justifications would never get seen.

These will be seen if adviser will not be killed with OOM -- can be a valuable warning to users. Propagation of `stack_info` on OOM will need to be handled differently - ideally with https://github.com/thoth-station/adviser/issues/1525 (openshift will need to provide OOM notification feature).

**Comment by Gkrumbach07** [comment]
I see it warns on a package specific basis. What about the case where there are many packages but they have a somewhat average sized version range. Could a justification be triggered for too large of a package requirements list?

**Comment by fridex** [comment]
> I see it warns on a package specific basis. What about the case where there are many packages but they have a somewhat average sized version range. Could a justification be triggered for too large of a package requirements list?

The message is triggered for two cases:

- no version range specification
- version range specification has no upper boundary (which is a specific case for the first one)

Both can cause troubles for future resolutions with new dependency releases. If users state something like `<1000.0.0` we can safely say that users checked version ranges and that means for us it is ok. If it semantically is ok, that is up to the users (we cannot judge it from the resolver). Does it answer your question?

**Comment by Gkrumbach07** [comment]
> Does it answer your question?

Yes, It all looks good then.

**Comment by fridex** [comment]
> > Does it answer your question?
> 
> Yes, It all looks good then.

Thanks! 👍🏻 

/approve

**Pull request merged**
