### PR TITLE
Add a wrap that adds information about Thoth s2i used

### PR DESCRIPTION
**Pull request by fridex**
Adds a pipeline unit that links to a page with Thoth s2i information used.

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Merging to continue with work.

CC @harshad16 looks like pytest results are not reported.

**Comment by harshad16** [comment]
> looks like pytest results are not reported.

noticed that the error message is large and cant be send a message.
will open a issue based on the error message, so we can solve it :+1:

**Pull request merged**
