### PR TITLE
Implement a sieve that filters out TensorFlow==2.4.0 on non-AVX2 CPU

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: #1616
Related: https://github.com/tensorflow/tensorflow/issues/45866 
Related: https://github.com/tensorflow/tensorflow/issues/45744

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm

**Comment by fridex** [comment]
@harshad16 thanks for the review!

/approve

**Comment by mihaimaruseac** [comment]
Just an update, TF 2.4.1 has been released and removes the AVX2 restriction. Apologies for the issues caused.

**Comment by fridex** [comment]
> Just an update, TF 2.4.1 has been released and removes the AVX2 restriction. Apologies for the issues caused.

No problem at all, thanks for the update!

**Pull request merged**
