### PR TITLE
Do not recommend using TensorFlow<2.3>=2.0 with NumPy>=1.19.0

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

https://github.com/numpy/numpy/pull/15355
https://github.com/tensorflow/tensorflow/commit/79518facb4b857af9d9d5df2da463fdbf7eb0e3e
https://github.com/tensorflow/tensorflow/issues/41902

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
There are patch releases incoming which remove the numpy constraints

**Comment by fridex** [comment]
> There are patch releases incoming which remove the numpy constraints

Hi @mihaimaruseac, thanks for letting us know. Which versions will include the patch? - I expect 2.3.1. Will it apply also for older minor releases? I'll adjust the recommendation accordingly.

**Comment by mihaimaruseac** [comment]
Sorry for the confusion, I just realized this issue is about numpy, not scipy. Numpy issue will be fixed forward in TF. Apologies again for the confusion

**Comment by fridex** [comment]
> Sorry for the confusion, I just realized this issue is about numpy, not scipy. Numpy issue will be fixed forward in TF. Apologies again for the confusion

No worries at all. Thanks for your input!

The wrong combination (both tf x pandas, tf x numpy) of packages will not occur for more recent releases (even for patch releases) based on the precomputed dependencies we store. So, we should be fine with this implementation.

Thanks again.

**Pull request merged**
