### PR TITLE
docs: Add pulp-python monitoring job

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/pulp-repository-sync-job/pull/3
Related: https://github.com/thoth-station/thoth-application/issues/1733

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... let's wait for naming sync

**Comment by goern** [comment]
Why is a pulp-hosted PI different that a simple-API one? or a warehouse API?

**Comment by fridex** [comment]
> Why is a pulp-hosted PI different that a simple-API one? or a warehouse API?

The job monitors new Python indexes created on pulp-python. In the case of pulp-python, we do not have a direct URL to one index as they are created dynamically. This job will detect new Python indexes created on Pulp and will automatically register them in Thoth. Other parts of the system will then schedule analyses of packages.

**Pull request merged**
