### PR TITLE
Document selective pre-releases

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/pull/1648
Related: https://github.com/thoth-station/thoth-application/issues/816

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/assign @tumido

@tumido, we have this experimental feature implemented, it's pending review. If you have some spare time, please have a look - your input for this will be valuable.

**Review by tumido — COMMENTED** [review]
/lgtm I love to see this thing to come alive! Thank you very much @fridex !

**Pull request merged**
