### PR TITLE
feat/remove custom validation use voluptous

### LINKED ISSUE #2407: Use voluptous validation instead of custom Presciption.validate
see https://github.com/alecthomas/voluptuous#multi-field-validation
/kind feature

Just and idea popping up while looking at the code with requirements between fields

### PR DESCRIPTION
**Pull request by VannTen**
## Related Issues and Dependencies
closes #2407

## This introduces a breaking change

- Yes

PrescriptionDuplicateUnitNameError is removed and incorporated in PrescriptionSchemaError

## This should yield a new module release

- Yes

### Description

Get rid of a bunch of manual code and put all schema semantics **inside** the voluptous schema.

This should avoid disconnection between the schema and the validation logic (discovered at least one while working on that) reduce our maintenance cost.

### CODE REVIEW

**Comment by codificat** [comment]
Not sure why the build-check is not reporting success here - a quick look at the [tekton dashboard](https://tekton.operate-first.cloud/#/pipelineruns) shows that the last pipelinerun (from the previous retest request) says: Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 8

**Comment by VannTen** [comment]
Might be the long built-time making prow forget the job ? Since adviser test the whole prescriptions repo.

**Comment by VannTen** [comment]
Let's retest in the morning, maybe there isn't as much load... (who knows)

/retest-required

**Comment by codificat** [comment]
Something isn't working with the build test here - but as last time I checked there were 0 failures from it, going to merge manually

**Pull request merged**
