### PR TITLE
Added the method to read version from project library to conf.py

### PR DESCRIPTION
**Pull request by harshad16**
Fixes: #233 

The PR contains:
- A method which reads a version from the project library and feeds it to conf.py.
Tested with cmd: `sphinx-build docs/source <destination>`
-  Some Pep8 changes.

### CODE REVIEW

**Comment by harshad16** [comment]
Sphinx document generation with setuptools gives priority to the configuration present in its options, if fields like `version` are not defined then these fields are taken from conf.py.
For multi-project documentation, I haven't figured out a handy way yet.

**Comment by fridex** [comment]
> Sphinx document generation with setuptools gives priority to the configuration present in its options, if fields like version are not defined then these fields are taken from conf.py.

So the priority is:

1. setup.py configuration
2. conf.py

Is that correct? If that is the case, having configuration propagated from setup.py should work just fine, right?

**Comment by harshad16** [comment]
> > Sphinx document generation with setuptools gives priority to the configuration present in its options, if fields like version are not defined then these fields are taken from conf.py.
> 
> So the priority is:
> 
> 1. setup.py configuration
> 2. conf.py
> 
> Is that correct? If that is the case, having configuration propagated from setup.py should work just fine, right?

Yes, that absolutely correct.

**Comment by fridex** [comment]
> Yes, that absolutely correct.

OK, so my assumption is that if you provide:

```python
'release': ('setup.py', release),
```

inside setup.py right after the version line, it will fix #233 with the current docs generation setup.

I'm not sure about multi-project docs generation (if we could reuse setup.py configuration), so let's make small steps and check where we get.

Could you try adding the python line above into setup.py and see if #233 gets fixed?

**Comment by harshad16** [comment]
> > Yes, that absolutely correct.
> 
> OK, so my assumption is that if you provide:
> 
> ```python
> 'release': ('setup.py', release),
> ```
> 
> inside setup.py right after the version line, it will fix #233 with the current docs generation setup.
> 
> I'm not sure about multi-project docs generation (if we could reuse setup.py configuration), so let's make small steps and check where we get.
> 
> Could you try adding the python line above into setup.py and see if #233 gets fixed?

Yes, adding release tag in setup.py configuration should suffice the issue.
I have added the release tag in setup.py, updated the pr, and if we need version or release to be picked up from conf.py
we can add them later if needed. :+1: 

can you please help me with the thoth-zuul error, I'm unable to understand it.

**Comment by fridex** [comment]
recheck

**Pull request merged**
