### PR TITLE
Add a step to tp correct version of NumPy with TF==1.13.1

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

See https://github.com/tensorflow/tensorflow/issues/25636

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
> /assign @fridex

@goern Why there is a need to do this? The PR was already approved by you.

/approve

**Comment by goern** [comment]
> > /assign @fridex
> 
> @goern Why there is a need to do this? The PR was already approved by you.

well, I am not a code OWNER, therefore my judgment is not as trustworthy as yours ;)

**Pull request merged**
