### PR TITLE
Do not score user's stack if Pipfile was adjusted

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Fixes: #2179

### CODE REVIEW

**Comment by fridex** [comment]
/wip

... I'll add a test case for this

**Comment by codificat** [comment]
Fixes https://github.com/thoth-station/thamos/issues/929

right?

**Comment by fridex** [comment]
> Fixes [thoth-station/thamos#929](https://github.com/thoth-station/thamos/issues/929)
> 
> right?

Yes, the issue could be transferred to the adviser, it is not related to Thamos CLI.

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by fridex** [comment]
> /wip
> 
> ... I'll add a test case for this

/unhold

... added

**Comment by codificat** [comment]
> Fixes https://github.com/thoth-station/thamos/issues/929
the issue was transferred, so now it
Fixes #2179 

/lgtm
/approve

thanks!

**Review by pacospace — APPROVED** [review]
lgtm!

**Pull request merged**
