### PR TITLE
Implement automatic schema checks in the testsuite

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
LGTM

**Comment by fridex** [comment]
> ```
> tests/conftest.py:194 in public function `state_verify_justification_schema`:
>         D202: No blank lines allowed after function docstring (found 1)
> ```

This is black vs pydocstyle issue. I'll try to rephrase the source code.

**Pull request merged**
