### PR TITLE
Convert to pyproject.toml

### PR DESCRIPTION
**Pull request by VannTen**

### CODE REVIEW

**Comment by VannTen** [comment]
related : thoth-station/nepthys#98

**Comment by goern** [comment]
/assign @VannTen 
@VannTen could you please check why `aicoe-ci/build-check` failed?

**Comment by VannTen** [comment]
Looks like assemble does not get thoth-adviser script. From the log I'm
not sure micropipenv actually install thoth-adviser by the way, only
its dependencies, I think. But that seem weird, how would it have worked
before in that case ?

**Comment by VannTen** [comment]
Looks like the s2i/assemble script does not the local package (adviser) without a setup.py... Something to do with micropipenv I think

**Comment by VannTen** [comment]
From the s2i image:
```bash
if [[ ( -f setup.py || -f setup.cfg ) && -z "$DISABLE_SETUP_PY_PROCESSING" ]]; then
  echo "---> Installing application ..."
  pip install .
fi
```

Great. I just got one more reason to dislike S2i :/.

**Comment by VannTen** [comment]
https://github.com/sclorg/s2i-python-container/pull/575

Looks like s2i-python upstream can work in that scenario. Maybe we can upgrade our version in thoth-s2i ?

**Comment by VannTen** [comment]
Possibly, I'm not too sure of what Python version we support

**Comment by frenzymadness** [comment]
Projects with pyproject.toml should now work in Python containers as well, see: https://github.com/sclorg/s2i-python-container/blob/92131e21ddc95cc25317333f0a1e62a821dfbd56/3.11/s2i/bin/assemble#L93-L96

**Comment by VannTen** [comment]
Yeah I've seen that. Unfortunately Thoth s2i images are a bit behind on upstream s2i :/

**Comment by harshad16** [comment]
> Possibly, I'm not too sure of what Python version we support

Atleast we should change it from 3.7 to 3.8 
as this repo is built on python 3.8
https://github.com/thoth-station/adviser/blob/ddde8d2ad59921c001c5725f3520c6691866cc22/Pipfile#L37
and on thoth side, the serving is for 3.8,3.9,3.10 based on different OS envs.

**Comment by harshad16** [comment]
can we have a rebase, so we can merge this

**Review by harshad16 — COMMENTED** [review]
alll looks good
though the build keeps failing at this https://github.com/thoth-station/adviser/blob/d869360b36a401e0cbbacefaf99aefc1e0f4e707/.s2i/bin/assemble#L18

the thoth-adviser installation generated from pyproject, is not showing the command.
still trying to find out the reason
/hold
till build is fixed

**Comment by VannTen** [comment]
Oh yeah I think I know why. the /usr/libexec/s2i/assemble is the one from thoth-s2i. Hence it does not use `pip install .` since it does not detect a setup.py or setup.cfg -> python package is not installed, thus, thoth-adviser command is not present. Should we switch to the upstream s2i for adviser right now ?

**Comment by VannTen** [comment]
> /hold
> till build is fixed

Isn't the build check required anyway ? I mean, prow is not gonna merge if the build fail right ? So no need to manually hold it ?

**Comment by harshad16** [comment]
> Isn't the build check required anyway ? I mean, prow is not gonna merge if the build fail right ? So no need to manually hold it ?

i added hold just for others, so no one actually merges it manually.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
/unhold 

thanks :+1:

**Pull request merged**
