### PR TITLE
Minor formatting changes in Kebechet docs

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
As we have all at one place now, I think we can remove https://thoth-station.ninja/kebechet/ page.

**Review by saisankargochhayat — APPROVED** [review]
Thanks! I was wondering why the runtime doesn't show fedora?

**Comment by saisankargochhayat** [comment]
> As we have all at one place now, I think we can remove https://thoth-station.ninja/kebechet/ page.

Could you point where the source code for it is?

**Pull request merged**
