### PR TITLE
WIP Introduce skip package step prescription unit

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: #1853

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
thanks for the update

**Comment by goern** [comment]
@fridex what is the status of this?

**Comment by fridex** [comment]
> @fridex what is the status of this?

The core logic should be done, I wanted to test it and have the heuristic stated in the comment implemented - thus merging was postponed (priority).

**Comment by goern** [comment]
@fridex is this still WIP?

**Comment by fridex** [comment]
> @fridex is this still WIP?

Low priority, no use case now.

**Comment by fridex** [comment]
Let's do it in a different way by extending the step unit. Adjustments directly in the step unit will be useful also in other cases.

/close

**Pull request closed without merging**
