### PR TITLE
Fix the URL path when pointing to the search Web UI

### PR DESCRIPTION
**Pull request by codificat**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/support/issues/219

## This introduces a breaking change

- No

## This should yield a new module release

- Yes (if a patch release is desired, although this is a minor bugfix)

## This Pull Request implements

Fix the URL that points to the Thoth Search web UI.

### Description

The correct path is `/search/advise/:id:`, e.g. https://thoth-station.ninja/search/advise/adviser-220520135456-693dce14c5adfe00/summary

Also, this PR includes an update to the pre-commit configuration, and related changes that pre-commit reported during a local run.

### CODE REVIEW

**Review by fridex — APPROVED** [review]
lgtm, thanks! 💯 Nice catch! 👍🏻

**Comment by codificat** [comment]
There are a bunch of mypy complaints in the pre-commit checks. These are unrelated to this PR and I believe recent PRs have been overriding these checks.

Should I update the pre-commit configuration to comment out the mypy checks for the time being?

**Comment by codificat** [comment]
The failing test is the `mypy` check and it is unrelated to the changes proposed here.

Looking at recent history in the repo, I see that other PRs have been merged with failing mypy tests, so I assume this is an outstanding item to fix (not sure how much #2173 is related)

Meanwhile though, and based on the above, I believe this one could go in...

What do you think @fridex / @harshad16 ?

**Comment by fridex** [comment]
Yes, I think this can go in 👍🏻 

Regardning failing mypy tests - do we use a new mypy version? I noticed tests started failing at some point without any source code changes.

**Comment by codificat** [comment]
> Regardning failing mypy tests - do we use a new mypy version? I noticed tests started failing at some point without any source code changes.

pre-commit plugins were updated at the end of March, including a change in mypy from `v0.770` to `v0.942` (https://github.com/thoth-station/adviser/commit/0726c6fecbfd296b7007c391cb36520cb3604c39#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L39

As this PR is taking the opportunity to further update pre-commit config, let me quickly try to revert that particular mypy version change...

**Comment by codificat** [comment]
> As this PR is taking the opportunity to further update pre-commit config, let me quickly try to revert that particular mypy version change...

Unfortunately, I just get different mypy errors when checking with `v0.770`, all of them on `thoth/adviser/unit.py`, which has not changed since the updated mypy... so, I really don't get what's going on here.

Probably worth creating a separate issue about mypy fixes though, and just merging that one in? (I don't have write perms to do that, though)

**Pull request merged**
