### PR TITLE
Add video demonstrating constaints.txt use

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/core/issues/271

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/approve

CC @harshad16 looks like we hit a memory limit:

Screenshot_2021-05-24_22-56-38

**Comment by harshad16** [comment]
> /approve
> 
> 
> Screenshot_2021-05-24_22-56-38

This pr would fix it https://github.com/thoth-station/adviser/pull/1869
seems like it was stuck at some ci pipeline.
This would ensure future pr ci checks success.

**Comment by fridex** [comment]
Thanks! 👍🏻

**Pull request merged**
