### PR TITLE
WIP: Provide guided information when assigning security score

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Closes: #1601 

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

@KPostOffice Looking into sources, we always propagate positive or neutral reward signal (in interval 1.0 and 0.0). Do we want to penalize packages with bad security score (interval from 1.0 for positive security score and -1.0 for negatively scored packages)?

**Comment by goern** [comment]
what do we need to push this forward?

**Comment by fridex** [comment]
> what do we need to push this forward?

Adjust score returned, we always return non-zero score.

**Comment by fridex** [comment]
This can be closed. Looking at sources, Kevin already adjusted messages so they are more descriptive to users based on data aggregated.

/close

**Pull request closed without merging**
