### PR TITLE
Introduce prescription

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/adviser/issues/1735

## This introduces a breaking change

- [x] No

## This Pull Request implements

With this change, Thoth operators will be able to supply prescriptions for the resolver. Prescription is a declarative way to configure resolver's behavior.

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

very well written :100:

**Comment by goern** [comment]
uhhhh wow!

/kind demo

**Comment by fridex** [comment]
I will merge this to have docs available. Will fix the pre-commit issues and provide tests in the next PR.

**Pull request merged**
