### PR TITLE
Prevent from OSError when the requirements string is too large

### PR DESCRIPTION
**Pull request by fridex**
When requriements are passed as a string, the instantiation method tries to open a
file. This causes OSError for large requirements and adviser terminates with a
traceback.

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
Earlier we used to del the` requirements_file`, do we need to do that?

**Comment by fridex** [comment]
> Earlier we used to del the` requirements_file`, do we need to do that?

It can be discarded, I think.

**Comment by saisankargochhayat** [comment]
@fridex Should we manually merge this?

**Comment by fridex** [comment]
> @fridex Should we manually merge this?

Let's do it :+1:

**Pull request merged**
