### PR TITLE
Remove no observations wrap

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/issues/1964

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by goern** [comment]
is this the same as #1966 ?

**Comment by fridex** [comment]
> is some parts of `test_produce.py` the same as #1966 ?

#1966 was built on top of this change (see commits). Both changes are required to deliver functionality, I wanted to finish it and not be blocked - hence the subsequent PR. Eigher this can go in first and #1966 can follow or directly merge #1966 and GitHub will close this one.

**Comment by goern** [comment]
thanks for the update @fridex 
@KPostOffice could you have a close look at #1966 and go ahead and approve it?

**Pull request closed without merging**
