### PR TITLE
Correct messages printed to users

### PR DESCRIPTION
**Pull request by fridex**
These messages correspond to the resolution process, not to adviser
specifically.

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by saisankargochhayat — APPROVED** [review]

**Comment by fridex** [comment]
All pre-commit checks passsed. Not sure why the error is reported.

CC @harshad16

**Comment by fridex** [comment]
> All pre-commit checks passsed. Not sure why the error is reported.
> 
> CC @harshad16

Sorry, might be the same issue as discussed in https://github.com/thoth-station/adviser/pull/1176#issuecomment-691860096

**Comment by harshad16** [comment]
> All pre-commit checks passsed. Not sure why the error is reported.
> 
> CC @harshad16

thanks frido , for pointing will check on it

**Comment by fridex** [comment]
> > All pre-commit checks passsed. Not sure why the error is reported.
> > CC @harshad16
> 
> thanks frido , for pointing will check on it

Cool, thanks! I'll keep this PR open then. :+1:

**Comment by harshad16** [comment]
figured out the issue, the resources for the pre-comiit are taken from cluster default which is not sufficient.
will be fixing this issue.

**Comment by fridex** [comment]
> figured out the issue, the resources for the pre-comiit are taken from cluster default which is not sufficient.
> will be fixing this issue.

It looks like it fails for this PR. Is there any action needed from my side to make pre-commit happy?

**Pull request merged**
